import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/Users/siddharthtripathi/Downloads/Pandas/netflix_titles.csv")

print(df.head())

df = df.dropna(subset=['type','release_year','rating','country','duration'])

type_count = df["type"].value_counts()
plt.figure(figsize=(6,4))
plt.bar(type_count.index, type_count.values,color=['skyblue','orange'])
plt.title("Count of Movies and TV Shows")
plt.xlabel("Type")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig('Netflix_Movies_vs_TV_shows.png', dpi=300, bbox_inches='tight')
plt.show()

rating_count = df["rating"].value_counts()
plt.figure(figsize=(8,6))
plt.pie(rating_count.values, labels=rating_count.index, autopct="%1.1f%%", startangle = 90)
plt.title("Distribution of Content Rating")
plt.tight_layout()
plt.savefig('Netflix_Content_Rating_Distribution.png', dpi=300, bbox_inches='tight')
plt.show()

movie_df = df[df['type'] == 'Movie'].copy()
movie_df['duration_int'] = movie_df['duration'].str.replace(' min', '').astype(int)
plt.figure(figsize=(8,6))
plt.hist(movie_df["duration_int"],bins=30, color="skyblue", edgecolor='black')
plt.title("Distribution of Movie Durations")
plt.xlabel("Duration (minutes)")
plt.ylabel("Number of Movies")
plt.tight_layout()
plt.savefig('Netflix_Movie_Duration_Distribution.png', dpi=300, bbox_inches='tight')
plt.show()

release_year_count = df['release_year'].value_counts().sort_index()
plt.figure(figsize=(10,6))
plt.scatter(release_year_count.index, release_year_count.values, color='lightgreen')
plt.title("Number of Releases per Year")
plt.xlabel("Release Year")
plt.ylabel("Number of Releases")
plt.tight_layout()
plt.savefig('Netflix_Releases_per_Year.png', dpi=300, bbox_inches='tight')
plt.show()

country_count = df["country"].value_counts().head(10)
plt.figure(figsize=(8,6))
plt.barh(country_count.index, country_count.values , color='coral', edgecolor='black')
plt.title("Top 10 Countries by Number of Titles")
plt.xlabel("Number of Titles")
plt.ylabel("Country")
plt.tight_layout()
plt.savefig('Netflix_Top_10_Countries.png', dpi=300, bbox_inches='tight')
plt.show()

content_by_year = df.groupby(['release_year',"type"]).size().unstack(fill_value=0)
fig, ax = plt.subplots (1,2,figsize=(12,5))

ax[0].plot(content_by_year.index, content_by_year['Movie'],color='skyblue', label='Movies')
ax[0].set_title('Movies Released Over Years')
ax[0].set_xlabel('Year')
ax[0].set_ylabel('Number of Movies')
ax[0].legend()  

ax[1].plot(content_by_year.index, content_by_year['TV Show'], color='orange', label='TV Shows')
ax[1].set_title('TV Shows Released Over Years')
ax[1].set_xlabel('Year')
ax[1].set_ylabel('Number of TV Shows')
ax[1].legend()  

fig.suptitle("Netflix Movies and TV Shows Over the Years", fontsize=16)
plt.tight_layout()
plt.savefig('Netflix_Movies_and_TV_Shows_Over_Years.png', dpi=300, bbox_inches='tight')
plt.show()